### ISSUE TITLE
Change documentation CI to trigger `Documenter` on tags.

### ISSUE THREAD

**Issue by codetalker7** [xKDR/CRRao.jl#88]
The current documentation CI is incomplete; `Documenter` is not triggered when new tags are made. This needs to be fixed. Also, it'll be a better idea to use already existing Julia actions in the CI (refer to https://github.com/xKDR/TSFrames.jl/blob/main/.github/workflows/documentation.yml).

**Comment by ShouvikGhosh2048** [comment]
CRRao:
```
name: Documentation

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    # can add tags if needed
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: julia-actions/setup-julia@latest
              with:
                version: '1.7.2'
                arch: x64
            - name: Install documentation dependencies
              run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
            - name: Build and deploy
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
              run: julia --project=docs/ docs/make.jl 
```

TSFrames:
```
name: Documentation

on:
    push:
        branches:
            - main
        tags: '*'
    pull_request:
        branches:
            - main
    # can add tags if needed
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: julia-actions/cache@v1
            - uses: julia-actions/julia-buildpkg@latest
            - uses: julia-actions/julia-docdeploy@latest
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
```
Are the specific details like versions/architectures/run commands in CRRao's file required, or should I just replace CRRao's documentation.yml with TSFrames?
